import { ArrowRight, Armchair, ExternalLink } from './Icons';

export default function Hero() {
  return <section id="cinema-hero" className="relative min-h-screen w-full flex flex-col justify-center items-center pt-24 pb-20 px-6 cinema-grid overflow-hidden border-b border-white/5">
    <div className="absolute inset-0 hero-glow-green pointer-events-none"/><div className="cinema-scanlines absolute inset-0"/>
    <div className="z-10 flex flex-wrap items-center justify-center gap-4 text-[11px] font-mono tracking-wider text-white/60 mb-8 bg-[#0a0e18]/80 border border-white/10 px-4 py-1.5 rounded-full backdrop-blur-md"><span className="text-red-400 font-bold">[REC]</span><span>00:24:09:30 IST</span><span className="text-white/20">•</span><span className="text-[#00d26a] font-semibold">MHSSCE CLOUD PRODUCTION // EVENT ARCHIVE 02</span><span className="text-white/20">•</span><span>LEVEL 100 → 200 INTENSIVE</span></div>
    <div className="z-10 flex items-center justify-center gap-4 sm:gap-8 my-4 relative max-w-xl w-full">
      <div className="flex flex-col items-center gap-2"><div className="w-20 h-20 sm:w-24 sm:h-24 rounded-2xl bg-[#171b26]/90 border-2 border-[#00d26a]/50 p-3.5 flex items-center justify-center shadow-[0_0_35px_rgba(0,210,106,0.35)]"><img alt="AWS SBG MHSSCE" className="w-full h-full object-contain" src="/images/awssbg-logo.png"/></div><span className="font-mono text-[10px] text-[#00d26a] uppercase font-bold tracking-wider">AWS SBG MHSSCE</span></div>
      <div className="flex-1 flex flex-col items-center justify-center relative px-2"><div className="h-[2px] w-full bg-gradient-to-r from-[#00d26a] via-[#38bdf8] to-[#00d26a] circuit-pulse shadow-[0_0_12px_#00d26a]"/><span className="mt-2 text-[10px] font-mono uppercase tracking-widest text-white/50 bg-[#0a0e18] px-2 border border-white/10 rounded">COLLABORATION</span></div>
      <div className="flex flex-col items-center gap-2"><div className="w-20 h-20 sm:w-24 sm:h-24 rounded-2xl bg-[#171b26]/90 border-2 border-[#38bdf8]/50 p-3.5 flex items-center justify-center shadow-[0_0_35px_rgba(56,189,248,0.25)]"><img alt="AWS" className="w-full h-full object-contain" src="/images/aws-logo.png"/></div><span className="font-mono text-[10px] text-[#38bdf8] uppercase font-bold tracking-wider">AWS OFFICIAL</span></div>
    </div>
    <div className="z-10 text-center mt-6 max-w-4xl mx-auto"><h1 className="text-4xl sm:text-6xl md:text-7xl font-extrabold tracking-tight text-white leading-[1.08]">From <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#00d26a] to-[#42ef83]">Clicks</span> to <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#38bdf8] to-[#7bd0ff]">Code</span>.</h1><p className="mt-6 text-base sm:text-xl text-[#8e95a5] max-w-2xl mx-auto leading-relaxed">Master the leap from manual console point-and-click operations to hardened, zero-port-22 AWS compute deployments automated by CloudFormation.</p></div>
    <div className="z-10 mt-8 w-full max-w-3xl"><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-4 rounded-2xl bg-[#171b26]/80 backdrop-blur-xl border border-white/10 shadow-2xl">
      {[['Date & Session','Sept 24, 2024','Tuesday Morning'],['Timecode','09:30 - 12:00','IST (2.5h Sprint)'],['Physical Venue','Seminar Hall','MHSSCE Byculla'],['Registration','Free Access','RSVP via Meetup']].map(([a,b,c],i)=><div key={a} className={`flex flex-col ${i<3?'border-r border-white/5':''} pr-2`}><span className="text-[10px] font-mono uppercase text-white/50">{a}</span><span className="text-white font-bold font-mono text-sm mt-0.5">{b}</span><span className="text-[#00d26a] text-[10px] font-mono">{c}</span></div>)}
    </div><div className="flex flex-wrap items-center justify-center gap-4 mt-8"><a className="inline-flex items-center gap-2.5 px-8 py-4 rounded-xl bg-[#00d26a] text-[#00210b] font-extrabold text-sm shadow-[0_0_30px_rgba(0,210,106,0.45)] hover:scale-[1.02] transition-all" href="https://www.meetup.com" target="_blank" rel="noreferrer"><Armchair/>RESERVE SEAT ON MEETUP<ExternalLink/></a><a className="inline-flex items-center gap-2 px-6 py-4 rounded-xl bg-[#262a35]/90 border border-white/10 text-white text-sm font-semibold" href="#story-pipeline">Begin Visual Journey <ArrowRight/></a></div></div>
    <a className="z-10 mt-12 flex flex-col items-center gap-2 text-white/50 hover:text-[#00d26a]" href="#story-pipeline"><span className="text-[10px] font-mono tracking-widest uppercase">SCROLL TO DIVE // SCENE 01</span><span className="w-5 h-9 rounded-full border-2 border-white/20 flex items-start justify-center p-1"><span className="w-1.5 h-2.5 rounded-full bg-[#00d26a] animate-bounce"/></span></a>
  </section>;
}
