import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowDown, ArrowUpRight, CalendarDays, Check, ChevronDown, Cloud, ExternalLink, LockKeyhole, Menu, Network, Server, ShieldCheck, Terminal, X, Zap} from 'lucide-react';
import './styles.css';

const MEETUP_URL = 'https://www.meetup.com/';

function App(){
  const [menu,setMenu]=useState(false); const [open,setOpen]=useState(null); const [scrolled,setScrolled]=useState(false);
  useEffect(()=>{const f=()=>setScrolled(scrollY>20); addEventListener('scroll',f); return()=>removeEventListener('scroll',f)},[]);
  const faqs=[['Do I need prior AWS experience?','No. We start with the basics and build toward a real deployment. Familiarity with Linux or the command line is useful, but not required.'],['What should I bring?','Bring a laptop, a browser, and your curiosity. We will share the practical setup instructions with registered attendees.'],['Will we use an SSH port?','No. A key part of the workshop is connecting to EC2 through Systems Manager Session Manager, without exposing SSH to the internet.'],['Is the workshop hands-on?','Yes. You will provision an EC2 instance manually first, then automate the same infrastructure with CloudFormation.']];
  return <div className="app">
    <nav className={scrolled?'nav nav-solid':'nav'}><a className="brand" href="#top"><span className="brand-mark">⌁</span><span>AWS SBG <b>MHSSCE</b></span></a><div className={menu?'links open':'links'}><a href="#workshop" onClick={()=>setMenu(false)}>Workshop</a><a href="#flow" onClick={()=>setMenu(false)}>Flow</a><a href="#takeaways" onClick={()=>setMenu(false)}>Takeaways</a><a href="#faq" onClick={()=>setMenu(false)}>FAQ</a><a className="nav-cta" href={MEETUP_URL} target="_blank" rel="noreferrer">Register <ArrowUpRight size={16}/></a></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></nav>
    <main id="top">
      <section className="hero"><div className="orb orb-a"/><div className="orb orb-b"/><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> AWS Student Builder Group · MHSSCE</div><h1>From <i>Clicks</i><br/>to <strong>Code.</strong></h1><p className="lead">A hands-on journey from your first EC2 instance to repeatable infrastructure — with security built in.</p><div className="hero-actions"><a className="primary" href={MEETUP_URL} target="_blank" rel="noreferrer">Reserve your seat <ArrowUpRight size={18}/></a><a className="secondary" href="#workshop">Explore workshop <ArrowDown size={16}/></a></div><div className="event-strip"><div><CalendarDays size={18}/><span><b>24 September 2026</b><small>Wednesday</small></span></div><div><span className="dotline"/><span><b>9:30 AM — 12:00 PM</b><small>Check-in from 9:30</small></span></div></div></div><div className="terminal-card"><div className="term-head"><span><i/><i/><i/></span><small>aws-session</small></div><div className="term-body"><p><em>$</em> aws ec2 run-instances</p><p className="dim">--instance-type t3.micro</p><p><em>✓</em> Instance launched</p><p className="dim">i-0a7f...mhssce</p><p><em>→</em> aws ssm start-session</p><div className="cursor"/></div><div className="term-badge"><LockKeyhole size={14}/> no :22 required</div></div></section>
      <section className="marquee"><div>EC2 <span>✦</span> SSM <span>✦</span> CLOUDFORMATION <span>✦</span> SECURITY <span>✦</span> AUTOMATION <span>✦</span> EC2 <span>✦</span> SSM <span>✦</span></div></section>
      <section className="intro" id="workshop"><div className="section-kicker">THE IDEA</div><div><h2>Build it once.<br/><span>Understand it forever.</span></h2><p>Not a slide deck. Not a copy-paste lab. You’ll see what happens behind the console, connect securely, then turn your work into infrastructure as code.</p></div></section>
      <section className="flow" id="flow"><div className="section-head"><div><div className="section-kicker">THE WORKSHOP</div><h2>Three moves.<br/><span>One real workflow.</span></h2></div><p>We go from manual understanding to safe, repeatable automation.</p></div><div className="steps"><Step n="01" icon={<Server/>} title="Launch" text="Provision an EC2 instance manually and understand the building blocks of AWS compute." tag="EC2 · CONSOLE"/><Step n="02" icon={<LockKeyhole/>} title="Connect" text="Use Systems Manager Session Manager to get a shell without opening an inbound SSH port." tag="SSM · NO SSH"/><Step n="03" icon={<Zap/>} title="Automate" text="Recreate the setup with CloudFormation and leave with an infrastructure-as-code mental model." tag="CLOUDFORMATION"/></div></section>
      <section className="takeaways" id="takeaways"><div className="takeaway-art"><div className="rings"><span/><span/><span/></div><div className="cube"><Cloud/></div><span className="float f1">EC2</span><span className="float f2">SSM</span><span className="float f3">YAML</span></div><div className="takeaway-copy"><div className="section-kicker">YOU’LL LEAVE WITH</div><h2>A clearer mental model<br/><span>of cloud infrastructure.</span></h2><div className="checklist"><p><Check/> Know the core pieces behind an EC2 deployment.</p><p><Check/> Connect to instances securely without public SSH.</p><p><Check/> Read and write a practical CloudFormation template.</p><p><Check/> Understand when manual work should become code.</p></div></div></section>
      <section className="speaker"><div><div className="section-kicker">YOUR GUIDE</div><h2>Learn by doing<br/><span>with Afreen Bano.</span></h2><p>A hands-on technical workshop designed to make AWS infrastructure feel less like a black box and more like something you can build.</p></div><div className="speaker-card"><div className="portrait">AB</div><div><b>Ms. Afreen Bano</b><span>Workshop Speaker</span></div><ArrowUpRight/></div></section>
      <section className="details"><div className="detail"><CalendarDays/><small>DATE</small><b>24 Sep 2026</b><span>Wednesday</span></div><div className="detail"><Terminal/><small>TIME</small><b>9:30 AM — 12 PM</b><span>Check-in starts at 9:30</span></div><div className="detail"><Network/><small>FORMAT</small><b>Hands-on</b><span>Technical workshop</span></div><div className="detail"><ShieldCheck/><small>ACCESS</small><b>Registered attendees</b><span>Details shared after signup</span></div></section>
      <section className="faq" id="faq"><div className="section-kicker">GOOD TO KNOW</div><h2>Questions, answered.</h2><div className="faq-list">{faqs.map(([q,a],i)=><div className={open===i?'faq-item active':'faq-item'} key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>0{i+1}</span><b>{q}</b><ChevronDown/></button>{open===i&&<p>{a}</p>}</div>)}</div></section>
      <section className="final"><div className="final-glow"/><div className="section-kicker">24 · 09 · 2026</div><h2>Ready to go<br/><i>from clicks to code?</i></h2><p>Seats are limited. Registration happens on Meetup.</p><a className="primary" href={MEETUP_URL} target="_blank" rel="noreferrer">Register on Meetup <ExternalLink size={17}/></a></section>
    </main><footer><span>© 2026 AWS Student Builder Group MHSSCE</span><span>From Clicks to Code</span><a href="#top">Back to top ↑</a></footer>
  </div>
}
function Step({n,icon,title,text,tag}){return <article className="step"><div className="step-top"><span>{n}</span>{icon}</div><h3>{title}</h3><p>{text}</p><small>{tag}</small></article>}
createRoot(document.getElementById('root')).render(<App/>);
